### ISSUE TITLE
quick start example throws exception

### ISSUE THREAD

**Issue by davidsblom** [nautechsystems/nautilus_data#4]
this quick start example throws an exception:

https://docs.nautilustrader.io/getting_started/quick_start.html#getting-the-sample-data

``` bash
curl https://raw.githubusercontent.com/nautechsystems/nautilus_data/main/scripts/hist_data_to_catalog.py | python -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2155  100  2155    0     0  25969      0 --:--:-- --:--:-- --:--:-- 28355
Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
ModuleNotFoundError: No module named 'scripts'
```

**Comment by cjdsellers** [comment]
Thanks for the report!

I just updated the repo, so this should work now.

**Comment by cjdsellers** [comment]
I had to fix it again, the curl is working now.

**Comment by davidsblom** [comment]
thanks for fixing the code. apologies to keep nagging about this, but the documentation needs to be updated as well to:

```python
from nautilus_trader.persistence.catalog import ParquetDataCatalog

catalog = ParquetDataCatalog("./catalog")
catalog.instruments()
```

**Comment by cjdsellers** [comment]
> thanks for fixing the code. apologies to keep nagging about this, but the documentation needs to be updated as well to:

Please nag away! It's really helping shake out all these little issues.

I've fixed this in the docs and also added a complete notebook to the examples for the quick start. It'll be on my next push to `develop` branch.

Thanks again!
